### ISSUE TITLE
Kernel version mismatch in boot log

### ISSUE THREAD

**Issue by CodeZombieCH** [rtr7/kernel#165]
I noticed that the latest kernel auto update PRs have a kernel version mismatch in the two boot logs. The PC Engines apu2c4 boot log appears to be one version behind.

### PC Engines apu2c4 boot log
Boot log comment: https://github.com/rtr7/kernel/pull/164#issuecomment-652495170
Mentions kernel version **Linux version 5.7.6**

```
[PC Engines apu2c4] [    0.000000] Linux version 5.7.6 (gokrazy@docker) (gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1), GNU ld (GNU Binutils for Debian) 2.28) #1 SMP Wed Mar 1 20:57:29 UTC 2017
[PC Engines apu2c4] [    0.000000] Command line: console=ttyS0,115200n8 root=PARTUUID=919b1544-02 ro init=/gokrazy/init panic=10 panic_on_oops=1
```

### qemu build log
Boot log comment: https://github.com/rtr7/kernel/pull/164#issuecomment-652495316
Mentions kernel version **Linux version 5.7.7**

```
[qemu] [    0.000000] Linux version 5.7.7 (gokrazy@docker) (gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1), GNU ld (GNU Binutils for Debian) 2.28) #1 SMP Wed Mar 1 20:57:29 UTC 2017
[qemu] [    0.000000] Command line: console=ttyS0,115200 root=PARTUUID=f970ed0d-02 ro init=/gokrazy/init panic=10 panic_on_oops=1
```

The same is true for
- https://github.com/rtr7/kernel/pull/163
- https://github.com/rtr7/kernel/pull/162

The images I created recently reported the correct kernel version (using a small sysinfo service I created), so this most probably only affects the automated tests. I do not know how these logs are generated but I thought it might be worth mentioning. Hope this helps.

**Comment by stapelberg** [comment]
Thanks, I’ll take a look in a bit. Did you by any chance check multiple older PRs and know if this is always a problem or only sometimes?

**Comment by stapelberg** [comment]
Looking at the logs, I can see:
```
Jul  1 17:41:43 dr bootery[1]: 2020/07/01 17:41:43 installing new boot image on bakery "PC Engines apu2c4"
Jul  1 17:41:43 dr bootery[1]: 2020/07/01 17:41:43 10351104 bytes in 214.193278ms, i.e. 46.087263 MiB/s
Jul  1 17:41:43 dr bootery[1]: 2020/07/01 17:41:43 446 bytes in 2.873167ms, i.e. 0.148038 MiB/s
2020/07/01 17:41:43 rebooting bakery "PC Engines apu2c4"
2020/07/01 17:41:43 [PC Engines apu2c4] [86392.535196] kexec_core: Starting new kernel
Jul  1 17:41:43 dr bootery[1]: 2020/07/01 17:41:43 [PC Engines apu2c4] [    0.000000] Linux version 5.7.6 (gokrazy@docker) (gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1), GNU ld (GNU Binutils for Debian) 2.28) #1 SMP Wed Mar 1 20:57:29 UTC 2017
Jul  1 17:41:43 dr bootery[1]: 2020/07/01 17:41:43 [PC Engines apu2c4] [    0.000000] Command line: console=ttyS0,115200n8 root=PARTUUID=919b1544-02 ro init=/gokrazy/init panic=10 panic_on_oops=1
```

The next older update says:
```
Jun 25 17:39:21 dr bootery[1]: 2020/06/25 17:39:21 installing new boot image on bakery "PC Engines apu2c4"
Jun 25 17:39:22 dr bootery[1]: 2020/06/25 17:39:22 10351104 bytes in 842.646426ms, i.e. 11.714975 MiB/s
Jun 25 17:39:22 dr bootery[1]: 2020/06/25 17:39:22 446 bytes in 2.855297ms, i.e. 0.148965 MiB/s
2020/06/25 17:39:22 rebooting bakery "PC Engines apu2c4"
Jun 25 17:39:22 dr bootery[1]: 2020/06/25 17:39:22 waiting for SUCCESS message in boot log on serial port
Jun 25 17:39:22 dr bootery[1]: 2020/06/25 17:39:22 [PC Engines apu2c4] [86399.492887] sd 0:0:0:0: [sda] Synchronizing SCSI cache
2020/06/25 17:39:22 [PC Engines apu2c4] [86399.548462] kexec_core: Starting new kernel
Jun 25 17:39:22 dr bootery[1]: 2020/06/25 17:39:22 [PC Engines apu2c4] [    0.000000] Linux version 5.7.5 (gokrazy@docker) (gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1), GNU ld (GNU Binutils for Debian) 2.28) #1 SMP Wed Mar 1 20:57:29 UTC 2017
Jun 25 17:39:22 dr bootery[1]: 2020/06/25 17:39:22 [PC Engines apu2c4] [    0.000000] Command line: console=ttyS0,115200n8 root=PARTUUID=919b1544-03 ro init=/gokrazy/init panic=10 panic_on_oops=1
```

That said, it’s still not clear to me why the wrong version seems to be used. I guess I’ll need to do a few manual updates to track this down.

**Comment by CodeZombieCH** [comment]
> Thanks, I’ll take a look in a bit. Did you by any chance check multiple older PRs and know if this is always a problem or only sometimes?
> 
> Edit: just checked the gokrazy/kernel PRs and the issue seems to affect those, too: https://gist.github.com/gokrazy-bot/151accd326e0445cbd3fa930e6553b58

This seems to affect all PRs starting from PR #101, with PR #103 being even two versions off (Linux version 5.3.6 vs Linux version 5.3.8).

**Comment by stapelberg** [comment]
Okay, I think I have a hunch as to what’s going on:

* when hitting the testboot handler directly with `curl -v -X PUT -H 'Content-Type: application/binary' --data-binary @/tmp/boot.img http://gokrazy:<secret>@dr:8037/testboot\?slug\=rtr7/kernel`, I almost immediately see the whole boot output, much faster than the device could ever reboot
* this suggests that the output of a previous boot is buffered (and indeed, I do reboot the device daily, so that makes sense). We use a `bufio.Scanner`, which by default has a 64K buffer as per https://golang.org/pkg/bufio/#pkg-constants
* I think instead of buffering, we should ensure the serial port is drained by the time we install the new image.
* We can do this by re-architecting the code such that one goroutine permanently reads from the serial port and dispatches onto a channel. From that channel, we can read non-blockingly (to drain) or blockingly (to verify).

**Comment by stapelberg** [comment]
This should be fixed for all new CI runs. I’ll try to keep an eye on it, but please let me know if you notice this problem (or anything else) again. Thanks!

**Comment by CodeZombieCH** [comment]
I just checked the logs of PR #166 and both logs contained the correct kernel version :+1:.
