### ISSUE TITLE
Why is this repo both kernel and firmware?

### ISSUE THREAD

**Issue by cweagans** [rtr7/kernel#217]
Super low priority on this -- if you don't have time, I completely understand.

Can you help me understand why this repo is both the kernel and firmware for the router7 project? For the other gokrazy targets, there are separate repos. Is it because the other targets are raspberry pi devices and need special firmware to boot, whereas this repo is more targeted at standard PC hardware and can just rely on the bios/uefi firmware to bring up the machine?

I'm working on putting together a gokrazy kernel repo for the official rpi kernel and i'm trying to get my head around the different moving pieces.

**Comment by stapelberg** [comment]
> s it because the other targets are raspberry pi devices and need special firmware to boot, whereas this repo is more targeted at standard PC hardware and can just rely on the bios/uefi firmware to bring up the machine?

Yes, that’s exactly right. There’s no way to specify “this target does not need firmware”, so we just set the firmware option to this repository, too.

**Comment by cweagans** [comment]
Excellent. Thanks for confirming!
